name: deploy

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

env:
  CROSS_VERSION: 0.1.16
  BOTAN_VERSION: 2.13.0
  PROJECT_NAME: enprot
  EXE_NAME: enprot

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Check version
        run: |
          set -euxo pipefail
          if [ "$(grep '^version' Cargo.toml | cut -d '"' -f2)" != "${GITHUB_REF#refs/tags/}" ]; then
            echo "Version tag does not match manifest"
            exit 1
          fi

  publish-snap:
    name: snap
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
          use_lxd: true
      - name: Install review-tools
        run: sudo snap install review-tools
      - name: Build
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/tags/}"
          sed -i "s/RELEASE_TAG/${RELEASE_TAG}/g" snap/snapcraft.yaml
          sg lxd -c 'snapcraft --use-lxd'
      - name: Publish
        run: |
          snapcraft upload *.snap --release stable

